apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update-deployment
  namespace: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 5
  minReadySeconds: 5       ### This much number of seconds a pod will take to get it ready. 
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1          ### one additional pod created 
      maxUnavailable: 1    ### one pod can be unavailable 
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: rolling-update-container
        image: nginx:1.25.5        ###     httpd:2.4.55
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 32Mi
            cpu: 10m
          limits:
            memory: 1Gi
            cpu: 2
---
apiVersion: v1
kind: Service
metadata:
  name: rolling-update-service
  namespace: demo
spec:
  selector:
    app: demo
  type: ClusterIP
  ports: 
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollingupdate-ingress
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
#  ingressClassName: nginx
  rules:
  - host: demo.singhritesh85.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rolling-update-service   ### Provide your service Name
            port:
              number: 80   
