apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-demo
  namespace: demo
spec:
  selector:
    matchLabels:
      app: recreate
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: recreate
    spec:
      containers:
      - name: recreate-demo-container
        image: nginx:1.25.5        ###  httpd:2.4.55
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 32Mi
            cpu: 10m
          limits:
            memory: 1Gi
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: recreate-demo-service
  namespace: demo
spec:
  selector: 
    app: recreate
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recreateapp-ingress
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
#  ingressClassName: nginx
  rules:
  - host: www.singhritesh85.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: recreate-demo-service   ### Provide your service Name
            port:
              number: 80   
