apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata: 
  name: yamada-project
  namespace: demo
spec:
  selector:
    matchLabels:
      app: yamada
  replicas: 5
  strategy:
    canary:
      canaryService: yamada-service-canary 
      stableService: yamada-service-stable
      steps:
      - setWeight: 20  ### Percentage of traffic to be sent to new version of application. 20% of 5 pods, 1 new pod will be created.
      - pause: {}  ### Indefinite pause and waiting for promote rollout 
      - setWeight: 40  ### Percentage of traffic to be sent to new version of application. 40% of 5 pods, 2 more new pods will be created.
      - pause: {duration: 10s}    ### pause for 10 seconds
      - setWeight: 60  ### Percentage of traffic to be sent to new version of application. 60% of 5 pods, n more new pods will be created, n value is taken in general to make it understandable to users. You can also consider replicas: 10 to make it more understandable to you.
      - pause: {duration: 10s}    ### pause for 10 seconds
      - setWeight: 80  ### Percentage of traffic to be sent to new version of application. 80% of 5 pods, n more new pods will be created, n value is taken in general to make it understandable to users. You can also consider replicas: 10 to make it more understandable to you.
      - pause: {duration: 10s}    ### pause for 10 seconds
  template:
    metadata:
      labels:
        app: yamada
    spec:
      containers:
      - name: zokosakiyachi-container
        image: httpd:2.4.55        ### nginx:1.25.5
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 28Mi
            cpu: 10m
          limits:
            memory: 1Gi
            cpu: 2
---
apiVersion: v1
kind: Service
metadata:
  name: yamada-service-stable
  namespace: demo
spec:
  selector:
    app: yamada
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: yamada-service-canary 
  namespace: demo
spec:
  selector:
    app: yamada
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-ingress
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
#    nginx.ingress.kubernetes.io/canary: "true"   ### It is a required annotation and it indicates canary deployment.
#    nginx.ingress.kubernetes.io/canary-weight: "30"  ### It indicates weight of the routing, there is a 30% chance that request will hit canary deployment. 
spec:
  rules:
  - host: www.singhritesh85.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yamada-service-stable
            port:
              number: 80   
          
        
