apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata: 
  name: yamada-project
  namespace: demo
spec:
  selector:
    matchLabels:
      app: yamada
  replicas: 5
  strategy:
    canary:
      canaryService: yamada-service-canary 
      stableService: yamada-service-stable
      steps:
      - setWeight: 20
      - pause: {}  ### Indefinite pause and waiting for promote rollout 
      - setWeight: 40
      - pause: {duration: 10s}
      - setWeight: 60
      - pause: {duration: 10s}
      - setWeight: 80
      - pause: {duration: 10s}
  template:
    metadata:
      labels:
        app: yamada
    spec:
      containers:
      - name: zokosakiyachi-container
        image: httpd:2.4.55
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 28Mi
            cpu: 10m
          limits:
            memory: 1Gi
            cpu: 2
---
apiVersion: v1
kind: Service
metadata:
  name: yamada-service-stable
  namespace: demo
spec:
  selector:
    app: yamada
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: yamada-service-canary 
  namespace: demo
spec:
  selector:
    app: yamada
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-ingress
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"   ### It is a required annotation and it indicates canary deployment.
    nginx.ingress.kubernetes.io/canary-weight: "30"  ### It indicates weight of the routing, there is a 30% chance that request will hit canary deployment. 
spec:
  rules:
  - host: www.singhritesh85.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yamada-service-stable
            port:
              number: 80   
          
        
